name: Ubuntu_vcpkg

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install needed libraries
      run: sudo apt-get update && sudo apt-get install -y libxrandr-dev xorg-dev libxinerama-dev
    - name: Install sdl and glfw via vcpkg
      run: python tools/vcpkg_install_third_parties.py

    - name: Configure
      run: |
          mkdir build
          cd build
          cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DHELLOIMGUI_USE_SDL_OPENGL3=ON  \
                -DHELLOIMGUI_USE_GLFW_OPENGL3=ON \
                -DHELLOIMGUI_USE_GLAD=ON         \
                -DHELLOIMGUI_BUILD_DOCS=ON       \
                ..
    - name: Build
      working-directory: build
      run: |
          make
