#!/usr/bin/env python3

import os
import sys

from narrative_programming import Resolver, split_lines


def parse_header_line(header_line):
    level = len(header_line.split(" ")[0])
    title = header_line[level + 1 :].rstrip()
    anchor_title = title.lower().replace(" ", "-")
    ignored_chars = [":", "+", ",", "!", '"', "(", ")", "?", "*", "`"]
    for ignored_char in ignored_chars:
        anchor_title = anchor_title.replace(ignored_char, "")
    return level, title, anchor_title


def repeat(s, nb):
    r = ""
    for i in range(nb):
        r = r + s
    return r


def is_header_line(line):
    return line.startswith("#") and not (line.startswith("#include"))


def remove_code_blocks(lines):
    filtered_lines = []
    in_code_block = False
    for line in lines:
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
        if not in_code_block:
            filtered_lines.append(line)
    return filtered_lines


def make_toc(file):
    with open(file, "r", newline='') as f:
        lines = f.readlines()
    lines = remove_code_blocks(lines)

    header_lines = [line[:-1] for line in lines if is_header_line(line)]
    toc = '<span id="TOC"/></span>\n\n'
    for header_line in header_lines:
        level, title, anchor_title = parse_header_line(header_line)
        toc = toc + "{}* [{}]({})\n".format(repeat("  ", level - 1), title, "#" + anchor_title)
    return toc


def read_text_file(path):
    if not os.path.isfile(path):
        return None
    with open(path, "r", newline='') as f:
        return f.read()


def process_md_file(input_file, output_file):
    """Resolves the transclusions (![[file.h#Name]], see narrative_programming.py) and the [TOC] of a .src.md file.
    An error (a missing file or name, a malformed annotation) fails."""
    with open(input_file, "r", newline='') as f:
        src = f.read()
    resolver = Resolver(read_text_file)
    resolved = resolver.resolve(split_lines(src), input_file)
    if resolver.errors:
        sys.exit(f"{input_file}:\n" + "\n".join(resolver.errors))

    src_basename = os.path.basename(input_file)
    content = f"<!-- This file is autogenerated from {src_basename} by tools/doc/process_md_docs.py -->\n"
    for line in resolved.splitlines(keepends=True):
        content = content + (make_toc(input_file) if line.startswith("[TOC]") else line)

    with open(output_file, "w", newline='') as f:
        f.write(content)


def process_main_readme(repo_dir: str):
    with open(repo_dir + "README.src.md", "r", newline='') as f:
        readme_src_content = f.read()
    with open(repo_dir + "/docs_src/intro.md", "r", newline='') as f:
        intro_content = f.read()

    readme_content = readme_src_content.replace("<!-- INTRO -->", intro_content)

    with open(repo_dir + "README.md", "w", newline='') as f:
        f.write(readme_content)


if __name__ == "__main__":
    this_dir = os.path.dirname(os.path.realpath(__file__)) + "/"
    repo_dir = this_dir + "/../../"
    hello_imgui_dir = repo_dir + "/src/hello_imgui/"

    process_main_readme(repo_dir)

    process_md_file(hello_imgui_dir + "doc_params.src.md", hello_imgui_dir + "doc_params.md")
    process_md_file(hello_imgui_dir + "doc_api.src.md", hello_imgui_dir + "doc_api.md")
